### ISSUE TITLE
Trying to Enqueue Downlink

### ISSUE THREAD

**Issue by offizium-berndstorath** [chirpstack/chirpstack-rest-api#18]
Request URL: `{{baseUrl}}/api/devices/04b6480450061804/queue`
Request Body:
```json
{
  "queueItem": {
    "confirmed": true,
    "data": "EA==",
    "fPort": 1,
    "id": "{{$randomUUID}}"
  }
}
```
Response Body:
```json
{
    "code": 13,
    "message": "Odd number of digits",
    "details": []
}
```

If I add something to data (e.g. `EEA==`) I get this
```json
{
    "code": 3,
    "message": "proto: (line 4:13): invalid value for bytes type: \"EEA==\"",
    "details": []
}
```

Maybe updating `grpc-gateway` fixes this

**Comment by VladislavGatsenko** [comment]
The description to the fields states that: 
`"id - string - ID (UUID). This is automatically generated on enqueue."`

Which means you don't need to specify it.

**Comment by VladislavGatsenko** [comment]
Everything you need to send Downlink in the example below:

`{
  "queueItem": {
    "confirmed": false,
    "data": "SGVsbG8gZnJvbSBHaUh1YiA6KQ==",
    "fPort": 123
  }
}`

![Swagger UI Downlink](https://github.com/user-attachments/assets/7f7942ca-ef66-4d84-b9bf-6fe584315cd4)

**Comment by VladislavGatsenko** [comment]
It's weird because it's supposed to work. I checked that such an error occurs when specifying an incorrect DevEUI: I added an extra space after it and as a result I got the same error as yours.
