### ISSUE TITLE
No Gateways

### ISSUE THREAD

**Issue by dedeweb** [chirpstack/chirpstack-rest-api#2]
When I call the webservice GET /api/gateways, the response is : 
```json
{
    "totalCount": 147,
    "result": []
}
````
Without any data in results...

**Comment by sagar-patel-sls** [comment]
Hi @dedeweb 

You need to pass the `limit` parameter in /api/gateways API request

![image](https://user-images.githubusercontent.com/43664335/191216816-15e530e8-ae58-49b3-ab39-9f1c97311081.png)

**Comment by dedeweb** [comment]
Hi,
I tried with limit parameter, but the result remains the same... 
I tried offset and tenant parameter too, but I can't get anything under result property...

**Comment by dedeweb** [comment]
Problem solved : my nginx reverse proxy was removing GET parameters from request. 
I'm closing the issue
