### ISSUE TITLE
"invalid length: expected length 32 for simple format, found 0" for multiple API endpoints?

### ISSUE THREAD

**Issue by ldorigo** [chirpstack/chirpstack-rest-api#4]
Hello,

I am trying to play with the API via the Swagger UI, and for a few different endpoints (that I found so far: `GET /api/applications`, `GET /api/devices`, `GET /api/device-profiles`) I get an error message, "invalid length: expected length 32 for simple format, found 0".

![Screenshot_20221020_153552](https://user-images.githubusercontent.com/8631181/196963512-ab9624b9-0acc-4ec0-ae34-f89ebf68b360.png)

I am on the latest version (4.0.2) of both chirpstack and chirpstack-rest-api.

Is this a bug or did I configure something wrong?

**Comment by ldorigo** [comment]
(It doesn't always fail - /api/gateways, for instances, works as expected)

**Comment by t-huyeng** [comment]
I had the some problem: 
You have to add `tentant-id` for applications or in case of the devices the `applicationId`.
See: https://forum.chirpstack.io/t/rest-api-bad-request/15138
